global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.
  # scrape_timeout is set to the global default (10s).
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label job=<job_name> to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['172.23.239.104::9090']
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      #      - targets: ['127.0.0.1:8063']
      - targets: ['34.93.245.170:8099', '34.93.245.170:8089', '34.93.245.170:8050' , '34.93.245.170:8093', '34.93.245.170:8015', '34.93.245.170:8111', '34.93.245.170:8087','34.93.245.170:6379','34.93.245.170:8088','34.93.245.170:8086','34.93.245.170:8010','34.93.245.170:8090','34.93.245.170:8060','34.93.245.170:8065']